### ISSUE TITLE
Smart Contract Feedback

### ISSUE THREAD

**Issue by StefPler** [banr1/transferable_vesting_contract#1]
Below follows some feedback for the Locker contract

### Code maturity & general comments
- Try to structure your code starting from structs and methods that are used / or will be used first. For example I would first introduce the Category struct and then the `Locker` & `CategoryRegistry` structs. In the same spirit I would also move the `transfer` method last since its the last call to be made, after a Locker has been created. 
- There is a small typo, in the Locker struct, the field `step` should probably be named `steps` or `total_steps` to be more descriptive.
- In the `register_category` method there is no need to pass the entire `LockerCap` object to prove you are the admin. You simply need to pass a reference like so `_: &LockerCap`. The `_` means that this variable won't be used anywhere so it informs the compiler that you are aware its not being read or mutated, it is simply passed to prove ownership. This way there is also no need to return the object back to the sender.
- Also in the `register_category`, you could assert if the `name` being used is already present in the VecSet so that you can inform the caller accordingly. Otherwise you could end up with duplicate entries.
- Suggestion: For simplicity, the `new` function can accept an entire coin, and the original balance can be that coin's entire balance.
- The `category.length() > 0` check in the `new` method is redundant because you are already checking the category against the registry which doesn't allow for 0 length strings.
- Try to use all of your assertions first when possible so that the gas cost is lower when a function call aborts.
- The category struct could have simply been a String field but is not wrong to keep as is.

### Security Considerations & Potential Limitations
- The Category Registry is using a `VecSet`. `VecSets` have a finite number of entries they can hold. If you would like it to contain more than 1000 items at some point, then consider using `Table` instead.
- The `new` function doesn't limit access other than checking the category. Is this desired? Should anyone be able to create new Lockers or only the `LockerCap` holder?
- The `new` function could take the clock instead of a `u64` for the start field. This way you ensure that no mistake can be made when setting the current start time in ms. Unless you want the start time to be in the future, in which case you can use `start: clock::timestamp_ms() + start`. So you ensure it starts on a future date.
- The `transfer` function also doesn't have any access control. This shouldn't pose a security concern but might require extra checks if someone else calls it for you because it would fail and you would expect it to succeed (it will have already been executed). 
- What happens if the amount placed in a Locker doesn't split exactly as it should in the pre specified steps? I believe there should be an assertion for this or some of the fields should be calculated internally so that there can be no mistake. For example, if you know the total balance and interval you can figure out programatically the total number of steps and the amount per step. This should reduce significantly the margin for error.

**Comment by banr1** [comment]
## Code maturity & general comments
- [x] Try to structure your code starting from structs and methods that are used / or will be used first. For example I would first introduce the Category struct and then the Locker & CategoryRegistry structs. In the same spirit I would also move the transfer method last since its the last call to be made, after a Locker has been created.
- [x] There is a small typo, in the Locker struct, the field step should probably be named steps or total_steps to be more descriptive.
- [x] (asking) In the register_category method there is no need to pass the entire LockerCap object to prove you are the admin. You simply need to pass a reference like so _: &LockerCap. The _ means that this variable won't be used anywhere so it informs the compiler that you are aware its not being read or mutated, it is simply passed to prove ownership. This way there is also no need to return the object back to the sender.
- [x] (asking) Also in the register_category, you could assert if the name being used is already present in the VecSet so that you can inform the caller accordingly. Otherwise you could end up with duplicate entries.
- [x] (asking) Suggestion: For simplicity, the new function can accept an entire coin, and the original balance can be that coin's entire balance.
- [x] The category.length() > 0 check in the new method is redundant because you are already checking the category against the registry which doesn't allow for 0 length strings.
- [x] Try to use all of your assertions first when possible so that the gas cost is lower when a function call aborts.
- [x] The category struct could have simply been a String field but is not wrong to keep as is.

## Security Considerations & Potential Limitations

- [x] The Category Registry is using a VecSet. VecSets have a finite number of entries they can hold. If you would like it to contain more than 1000 items at some point, then consider using Table instead.
- [x] The new function doesn't limit access other than checking the category. Is this desired? Should anyone be able to create new Lockers or only the LockerCap holder?
- [x] The new function could take the clock instead of a u64 for the start field. This way you ensure that no mistake can be made when setting the current start time in ms. Unless you want the start time to be in the future, in which case you can use start: clock::timestamp_ms() + start. So you ensure it starts on a future date.
- [x] (asking) The transfer function also doesn't have any access control. This shouldn't pose a security concern but might require extra checks if someone else calls it for you because it would fail and you would expect it to succeed (it will have already been executed).
- [x] (asking) What happens if the amount placed in a Locker doesn't split exactly as it should in the pre specified steps? I believe there should be an assertion for this or some of the fields should be calculated internally so that there can be no mistake. For example, if you know the total balance and interval you can figure out programatically the total number of steps and the amount per step. This should reduce significantly the margin for error.

**Comment by banr1** [comment]
> Try to structure your code starting from structs and methods that are used / or will be used first. For example I would first introduce the Category struct and then the Locker & CategoryRegistry structs. In the same spirit I would also move the transfer method last since its the last call to be made, after a Locker has been created.

> There is a small typo, in the Locker struct, the field step should probably be named steps or total_steps to be more descriptive.

> Try to use all of your assertions first when possible so that the gas cost is lower when a function call aborts.

> 

You're absolutely right. I've made the changes accordingly.

>  Try to use all of your assertions first when possible so that the gas cost is lower when a function call aborts.

Sounds good! I'll change it to that.

> The Category Registry is using a VecSet. VecSets have a finite number of entries they can hold. If you would like it to contain more than 1000 items at some point, then consider using Table instead.

It's not a problem, as I was imagining there would be at most about 10 items.

**Comment by banr1** [comment]
@StefPler 
1.  > In the register_category method there is no need to pass the entire LockerCap object to prove you are the admin. You simply need to pass a reference like so _: &LockerCap. The _ means that this variable won't be used anywhere so it informs the compiler that you are aware its not being read or mutated, it is simply passed to prove ownership. This way there is also no need to return the object back to the sender.

    I'm getting an error like this. What do you think?

    > Invalid return
    > locker.move(70, 34): The parameter '_' still contains a value. The value does not have the 'drop' ability and must be consumed before the function returns
    > locker.move(70, 37): The type 'transferable_vesting_locker::locker::LockerCap' does not have the ability 'drop'
    > locker.move(19, 19): To satisfy the constraint, the 'drop' ability would need to be added here

2. > Also in the register_category, you could assert if the name being used is already present in the VecSet so that you can inform the caller accordingly. Otherwise you could end up with duplicate entries.

    I also considered adding that, but I felt that if we were to add it, there wouldn't be much difference from using a vector here. What do you think?
    This translation captures the essence of the original Japanese text, conveying the speaker's thought process and seeking opinion from the listener. The mention of vector is kept as-is, as it appears to be a programming-related term that doesn't require translation.

3. >  The category.length() > 0 check in the new method is redundant because you are already checking the category against the registry which doesn't allow for 0 length strings.

    I understood. I got it.

**Comment by banr1** [comment]
1. >  The new function could take the clock instead of a u64 for the start field. This way you ensure that no mistake can be made when setting the current start time in ms. Unless you want the start time to be in the future, in which case you can use start: clock::timestamp_ms() + start. So you ensure it starts on a future date.

    Certainly, this will definitely be executed in the future. However, when considering the user experience (UX), it's more intuitive to set a specific date and time timestamp (as we might want to start at a round time). Therefore, we'll add a single line to assert that the timestamp is indeed in the future.

2. > The new function doesn't limit access other than checking the category. Is this desired? Should anyone be able to create new Lockers or only the LockerCap holder?

    It was intentional, but you're right, it does seem better to include it as an argument. I'll do that.

**Comment by banr1** [comment]
(I wanted to link my commit by including '#1' in the commit message, but I forgot to do so. I've already made the commit.)

https://github.com/banr1/transferable_vesting_locker/commit/805f02d93061f6bafe4c88bbbc3f9a0177ac3648

**Comment by banr1** [comment]
> Suggestion: For simplicity, the new function can accept an entire coin, and the original balance can be that coin's entire balance.

I also considered that option, but thinking of this as an irreversible action that can only be done once, I thought the current method might be more convenient.
Considering security and other factors, do you think it's better to accept the entire coin?

**Comment by banr1** [comment]
> What happens if the amount placed in a Locker doesn't split exactly as it should in the pre specified steps? I believe there should be an assertion for this or some of the fields should be calculated internally so that there can be no mistake. For example, if you know the total balance and interval you can figure out programatically the total number of steps and the amount per step. This should reduce significantly the margin for error.

I believe it's not possible for the amount to be undivided because the 'original_amount' is calculated from the 'steps' and 'amount_per_step' given as arguments. Of course, we could design it to take 'duration' and 'total_amount' as arguments, but I think the former approach is easier to specify.

**Comment by banr1** [comment]
> The transfer function also doesn't have any access control. This shouldn't pose a security concern but might require extra checks if someone else calls it for you because it would fail and you would expect it to succeed (it will have already been executed).

I think it might be more risky to require a `LockerCap` for this. If the private key of the person holding the `LockerCap` is hacked, we can't be sure if it will actually be executed. Moreover, even without hacking, the `LockerCap` owner might suddenly refuse to execute it after the fifth time out of spite.
Since this isn't in a 'claim' format, I believe this possibility is problematic. If we allow anyone to execute it (we're trying to implement a non-claim type to reduce user burden, so we'll execute it from our end), even if the LockerCap owner becomes negligent in the worst-case scenario, the receiver themselves or other well-intentioned individuals can still execute it.

**Comment by StefPler** [comment]
> @StefPler
> 
> 1. > In the register_category method there is no need to pass the entire LockerCap object to prove you are the admin. You simply need to pass a reference like so _: &LockerCap. The _ means that this variable won't be used anywhere so it informs the compiler that you are aware its not being read or mutated, it is simply passed to prove ownership. This way there is also no need to return the object back to the sender.
>    
>    
>    I'm getting an error like this. What do you think?

You should pass just the reference, not the entire object. Should be `_: &LockerCap` not `_: LockerCap`

>    > Invalid return
>    > locker.move(70, 34): The parameter '_' still contains a value. The value does not have the 'drop' ability and must be consumed before the function returns
>    > locker.move(70, 37): The type 'transferable_vesting_locker::locker::LockerCap' does not have the ability 'drop'
>    > locker.move(19, 19): To satisfy the constraint, the 'drop' ability would need to be added here
> 2. > Also in the register_category, you could assert if the name being used is already present in the VecSet so that you can inform the caller accordingly. Otherwise you could end up with duplicate entries.
>    
>    
>    I also considered adding that, but I felt that if we were to add it, there wouldn't be much difference from using a vector here. What do you think?

VecSet just provides a different API but internally uses a vector so its a matter of which API fits your needs best. I would still suggest checking for this so that it doesn't introduce any unwanted bugs later on.

>    This translation captures the essence of the original Japanese text, conveying the speaker's thought process and seeking opinion from the listener. The mention of vector is kept as-is, as it appears to be a programming-related term that doesn't require translation.
> 3. > The category.length() > 0 check in the new method is redundant because you are already checking the category against the registry which doesn't allow for 0 length strings.
>    
>    
>    I understood. I got it.

**Comment by StefPler** [comment]
> I also considered that option, but thinking of this as an irreversible action that can only be done once, I thought the current method might be more convenient.

Security wise its safer to use the entire coin since the user can split the desired amount before calling this method. Otherwise someone might not be as comfortable giving a very large coin. It might be ok here if its an admin action since no user will be calling this but its how we usually handle coins

**Comment by banr1** [comment]
> You should pass just the reference, not the entire object. Should be _: &LockerCap not _: LockerCap

I understood!

**Comment by banr1** [comment]
> VecSet just provides a different API but internally uses a vector so its a matter of which API fits your needs best. I would still suggest checking for this so that it doesn't introduce any unwanted bugs later on.

I see. In that case, I'll add an assertion.

**Comment by banr1** [comment]
> Security wise its safer to use the entire coin since the user can split the desired amount before calling this method. Otherwise someone might not be as comfortable giving a very large coin. It might be ok here if its an admin action since no user will be calling this but its how we usually handle coins

I see, that makes sense. Since it's essentially the administrators who are doing the splitting, I hadn't given it much thought. But you're right, we can just use a script to split it when we process it. So, I'll go ahead and handle it that way.
